---
- name: Update apt cache.
  apt: update_cache=yes cache_valid_time=600
  when: ansible_os_family == 'Debian'

- name: Install certbot package dependencies
  ansible.builtin.package:
    name: '{{ _certbot_packages }}'
    state: present
  become: true
  register: install_certbot_packages
  when: _certbot_packages is defined
  tags:
    - install
    - apt
    - update_cache
